'use client'

import { useEffect, useState } from 'react'
import { getAIRecommendations } from '@/lib/api'
import { Lightbulb, ArrowRight, RefreshCw } from 'lucide-react'
import Link from 'next/link'

type Recommendation = {
  title: string
  description: string
  suggested_nl_segment: string
  suggested_channel: string
  estimated_impact: string
}

const TYPE_COLORS: Record<string, string> = {
  'WhatsApp': 'bg-green-500/10 text-green-400 border-green-500/20',
  'SMS': 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  'Email': 'bg-orange-500/10 text-orange-400 border-orange-500/20',
  'RCS': 'bg-violet-500/10 text-violet-400 border-violet-500/20',
}

export default function RecommendationsPage() {
  const [recs, setRecs] = useState<Recommendation[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)

  const loadRecs = async () => {
    try {
      const data = await getAIRecommendations()
      
      if (Array.isArray(data)) {
        setRecs(data)
      } else if (data && typeof data === 'object') {
        
        const firstArray = Object.values(data).find(v => Array.isArray(v))
        setRecs((firstArray as Recommendation[]) || [])
      }
    } catch(e) {
      console.error('failed to get recs', e)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadRecs()
  }, [])

  const handleRefresh = async () => {
    setRefreshing(true)
    await loadRecs()
    setRefreshing(false)
  }

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">AI Recommendations</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Proactive growth opportunities generated by AI analysis
          </p>
        </div>
        <button
          onClick={handleRefresh}
          disabled={refreshing}
          className="flex items-center gap-2 text-xs px-3 py-2 rounded-lg border border-border hover:bg-accent transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-3 h-3 ${refreshing ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {loading ? (
        <div className="text-center text-muted-foreground text-sm py-10">
          Generating recommendations...
        </div>
      ) : recs.length === 0 ? (
        <div className="gradient-border rounded-xl p-10 text-center">
          <Lightbulb className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
          <p className="text-muted-foreground text-sm">No recommendations generated.</p>
          <p className="text-xs text-muted-foreground/60 mt-1">Make sure the backend is running.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {recs.map((rec, i) => (
            <div key={i} className="gradient-border rounded-xl p-5 flex flex-col hover:glow-purple transition-all duration-200">
              <div className="flex items-start justify-between mb-3">
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Lightbulb className="w-4 h-4 text-primary" />
                </div>
                <span className={`text-xs px-2 py-0.5 rounded-full border ${TYPE_COLORS[rec.suggested_channel] || 'bg-accent text-foreground border-border'}`}>
                  {rec.suggested_channel}
                </span>
              </div>

              <h3 className="text-sm font-bold text-foreground mb-2">{rec.title}</h3>
              <p className="text-xs text-muted-foreground leading-relaxed flex-1">{rec.description}</p>

              <div className="mt-4 pt-4 border-t border-border">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs text-muted-foreground">Estimated Impact</span>
                  <span className="text-sm font-bold text-green-400">{rec.estimated_impact}</span>
                </div>

                <div className="mb-3">
                  <p className="text-xs text-muted-foreground mb-1">Suggested Segment</p>
                  <p className="text-xs text-foreground bg-background border border-border rounded px-2 py-1.5 italic">
                    "{rec.suggested_nl_segment}"
                  </p>
                </div>

                <Link
                  href={`/agent?goal=${encodeURIComponent(rec.suggested_nl_segment)}`}
                  className="w-full flex items-center justify-center gap-1.5 text-xs py-2 rounded-lg bg-primary/10 border border-primary/30 text-primary hover:bg-primary/20 transition-colors"
                >
                  Launch with AI Agent
                  <ArrowRight className="w-3 h-3" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}

      
      <div className="gradient-border rounded-xl p-5 mt-4">
        <h3 className="text-sm font-semibold text-foreground mb-3">How AI Recommendations Work</h3>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {[
            {
              step: '1',
              title: 'Database Scan',
              desc: 'The opportunity scanner runs on a schedule, auditing purchase trends, churn scores, and engagement patterns.'
            },
            {
              step: '2',
              title: 'Rule Evaluation',
              desc: 'Heuristic rules detect patterns: churn cohorts, cross-sell gaps, upsell candidates, and channel inefficiencies.'
            },
            {
              step: '3',
              title: 'AI Synthesis',
              desc: 'The Insights Agent compiles findings into actionable cards with revenue estimates and pre-drafted campaign templates.'
            },
          ].map((item) => (
            <div key={item.step} className="flex gap-3">
              <div className="w-6 h-6 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center shrink-0 mt-0.5">
                <span className="text-xs text-primary font-bold">{item.step}</span>
              </div>
              <div>
                <p className="text-sm font-medium text-foreground">{item.title}</p>
                <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
